source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # Yandex Mobile Ads SDK
  pod 'YandexMobileAds', '8.5.0'

  # Yandex Mobile Ads Mediation
  pod 'YandexMobileAdsMediation', '8.5.0'
  pod 'AppLovinYandexMobileAdsAdapters', '13.6.4.0'
  pod 'BigoADSYandexMobileAdsAdapters', '5.0.6.5'
  pod 'ChartboostYandexMobileAdsAdapters', '9.13.0.1'
  pod 'GoogleYandexMobileAdsAdapters', '13.8.0.0'
  pod 'InMobiYandexMobileAdsAdapters', '11.4.0.1'
  pod 'IronSourceYandexMobileAdsAdapters', '9.3.0.5'
  pod 'MintegralYandexMobileAdsAdapters', '8.0.7.5'
  pod 'MyTargetYandexMobileAdsAdapters', '5.36.2.5'
  pod 'PangleYandexMobileAdsAdapters', '8.1.0.1'
  pod 'StartAppYandexMobileAdsAdapters', '4.14.0.1'
  pod 'UnityAdsYandexMobileAdsAdapters', '4.20.0.0'
  pod 'VungleYandexMobileAdsAdapters', '7.7.5.1'
  pod 'YandexMobileAdsAdMobAdapters', '8.5.0.0'
  pod 'zMaticooYandexMobileAdsAdapters', '1.5.6.5'

  # ComposeApp framework is built via Gradle embedAndSignAppleFrameworkForXcode task
end
